#!/bin/sh
echo "1234" | sudo -S iptables -D INPUT -i ens33 ! -s 192.168.133.0/24 -j DROP
echo "Acceso a Internet abierto"
uuencode /home/ovic/Ingenieria/Informes/programa.txt programa.txt | mail -s "Programa" pista@ovic.com
echo "Se ha enviado por email el programa a pista"
echo "1234" | sudo -S iptables -A INPUT -i ens33 ! -s 192.168.133.0/24 -j DROP
echo "Acceso a Internet restringido"
